language: python
sudo: true
dist: xenial
python:
  - "3.7"
  - "3.6"
install:
  - sudo apt-get install cargo
  - sudo cargo install tokei
  - pip install codecov
  - pip install -e ".[test]"
script:
  - bin/test.sh
after_success:
  - codecov